# Generated by Django 3.0 on 2019-12-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
    ]
