# Generated by Django 3.0 on 2019-12-16 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20191214_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
