# Generated by Django 3.0 on 2019-12-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
